import tensorflow as tf

# Third-party
from src.models.user import UserEmbeddingModel


class QueryTower(tf.keras.Model):

    def __init__(
        self,
        dataset,
        embedding_dim,
    ) -> 'QueryTower':
        """
            Query Tower
        """
        super().__init__()

        self.embedding_model = UserEmbeddingModel(
            dataset = dataset,
            embedding_dim = embedding_dim
        )


    def call(
        self,
        inputs: tf.Tensor,
    ) -> tf.Tensor:
        """
            Calls the model on the input tensor.

            Parameters:
                - inputs (tf.Tensor): A tensor containing input data to be processed by the embedding model. 

            Returns:
                - embedding (tf.Tensor): The output tensor containing the concatenated embeddings generated by the model. 
        """
        embedding: tf.Tensor = self.embedding_model(inputs)
        return embedding
