from copy import deepcopy
import tensorflow as tf
import tensorflow_recommenders as tfrs

class Tower(tf.keras.Model):

    def __init__(
        self,
        embedding_model: tf.keras.Model,
        cross_layer: tfrs.layers.dcn.Cross = None,
        deep_layers: tf.keras.Sequential = None,
    ) -> 'Tower':
        """
            Tower Model.
            
            Parameters:
                - embedding_model (tf.keras.Model): a model that transforms inputs to embeddings.
                - cross_layer (tfrs.layers.dcn.Cross): a Cross layer to perform feature crossing. Defaults to `None`.
                - deep_layers (tf.keras.Sequential): a sequence of layers to perform deep feature interaction. Defaults to `None`.
        
        """
        super().__init__()

        self._embedding_model = embedding_model
        self._cross_layer = deepcopy(cross_layer)
        self._deep_layers = deepcopy(deep_layers)


    def call(
        self,
        inputs: tf.Tensor,
    ) -> tf.Tensor:
        """
            Calls the model on the input tensor.

            Parameters:
                - inputs (tf.Tensor): A tensor containing input data to be processed by the embedding model. 

            Returns:
                - (tf.Tensor): The output tensor generated by the model. 
        """
        x = self._embedding_model(inputs)
        x = self._cross_layer(x) if self._cross_layer else x
        x = self._deep_layers(x) if self._deep_layers else x
        return x
